services:
  mysql:
    image: mysql:8
    container_name: notification_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: notification_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: notification_cache
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: notification_queue
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql_data:

